#!/bin/bash
# If you want to build strace2ds library, just run this script.
# If you want to build and install, run this script with 'install' argument. Ex: ./buildall install

function runcmd
{
    echo "CMD: $@"
    sleep 0.2
    $@
    ret=$?
    if test $ret -ne 0 ; then
	exit $ret
    fi
}

runcmd /bin/rm -fr BUILD
runcmd mkdir -p BUILD

# runcmd mkdir -p xml
# runcmd cd tables
# runcmd perl gen-xml-enums.pl
# runcmd cd ../

# runcmd cp -r ./xml BUILD
runcmd cd BUILD
runcmd cmake ../
runcmd make clean

# If all you're changing is C/C++ code, just "cd BUILD" and run next two commands.
numberOfCores="$(nproc --all)"
runcmd make -j$numberOfCores
if [ "$#" -eq 1 ] && [ "$1" = "install" ]
then
    runcmd make install
fi
